# kitty term conf by storedbyte

# font
font_family Maple Mono 
font_size 12.0

# transparency and blur
background_opacity 0.80
background_blur 1

# theme switcher location
include ~/.config/themes/active/kitty.conf

